name: $USER
services:
  devkit:
    container_name: $USER-devkit
    build:
      context: .
      dockerfile: devkit.Dockerfile
      target: dev
    ports:
      - $FOXGLOVE_PORT:8765 # Foxglove
    networks:
      - simulation
    depends_on:
      - simulator
    volumes:
      - /home/$USER/.vscode/:/home/autodrive_devkit/.vscode/
      - /home/$USER/dev_ws:/home/autodrive_devkit/src/dev_ws
      - /home/$USER/.Xauthority:/root/.Xauthority
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
      - DISPLAY=$DISPLAY_DOCKER
      - XAUTHORITY=/root/.Xauthority
#    gpus:
#      - count: all
#        capabilities:
#          - gpu
  simulator:
    container_name: $USER-simulator
    build:
      context: .
      dockerfile: simulator.Dockerfile
    environment:
      - DEVKIT_IP=$USER-devkit
    networks:
      - simulation

networks:
  simulation:
    driver: bridge
