name: $USER
# TODO:
# - Add une cronjob pour restart et update le serveur chaque semaine
# - S'assurer que les logs docker bloat pas le systeme
# - Symlink /shared_ws dans le home des users
# - Update la doc et tester sur windows

services:
  devkit:
    container_name: $USER-devkit
    build:
      context: .
      dockerfile: devkit.Dockerfile
      target: dev
      args:
        - USER_UID=$UID
    ports:
      - $FOXGLOVE_PORT:8765 # Foxglove
    networks:
      - simulation
    depends_on:
      - simulator
    volumes:
      - /home/$USER/.vscode/:/home/autodrive_devkit/.vscode/
      - /home/$USER/dev_ws:/home/autodrive_devkit/src/dev_ws
      - /home/$USER/.Xauthority:/home/autodrive_devkit/.Xauthority
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
      - DISPLAY=$DISPLAY_DOCKER
      - XAUTHORITY=/home/autodrive_devkit/.Xauthority
      - FOXGLOVE_PORT=$FOXGLOVE_PORT
#    gpus:
#      - count: all
#        capabilities:
#          - gpu
  simulator:
    container_name: $USER-simulator
    build:
      context: .
      dockerfile: simulator.Dockerfile
    environment:
      - DEVKIT_IP=$USER-devkit
    networks:
      - simulation

networks:
  simulation:
    driver: bridge
