name: $USER
services:
  devkit:
    container_name: $USER-devkit
    build:
      context: .
      dockerfile: devkit.Dockerfile
      target: final
      args:
        - USER_UID=$UID
    ports:
      - $FOXGLOVE_PORT:8765 # Foxglove
    networks:
      - simulation
    depends_on:
      - simulator
    volumes:
      - /home/$USER/.Xauthority:/home/autodrive_devkit/.Xauthority
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
      - DISPLAY=$DISPLAY_DOCKER
      - XAUTHORITY=/home/autodrive_devkit/.Xauthority
      - FOXGLOVE_PORT=$FOXGLOVE_PORT
#    gpus:
#      - count: all
#        capabilities:
#          - gpu
  simulator:
    container_name: $USER-simulator
    build:
      context: .
      dockerfile: simulator.Dockerfile
    environment:
      - DEVKIT_IP=$USER-devkit
    networks:
      - simulation

networks:
  simulation:
    driver: bridge